BM-1689: attach error context to retry max failure in bento (#1197)
Currently, these proving/task errors are more tedious to get the error
context from as it requires querying the bento logs. This change just
applies the error context to the `retry max hit` so it's easier to see
what's going on.

```
$ RUST_LOG=info bento_cli --iter-count 2000
2025-10-02T15:00:40.214683Z  INFO bento_cli: image_id: 945b1314389246cce502d15fa42b41c2f4301620a68cdd71619cab87da8d030d | input_id: d333445d-c243-437a-9869-9df11c9ea80d
2025-10-02T15:00:40.216976Z  INFO bento_cli: STARK job_id: 00758d72-a9bf-4564-8aaa-676d3d015b0d
2025-10-02T15:00:40.217284Z  INFO bento_cli: STARK Job running....
Error: Job failed: 00758d72-a9bf-4564-8aaa-676d3d015b0d - retry max hit: Prove failed: Test segment proving failure
```